
{% set data = load_setup_py_data() %}

package:
  name: confiddler
  
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  requires:
    - pytest 4.0.*
    - pytest-cov
    - numpy

  commands:
    - pytest -s --tb=native --cov=confiddler --pyargs confiddler.tests
    - cp .coverage /tmp/ # for the travis build

about:
  home: https://github.com/stuarteberg/confiddler
  summary: Utilities for defining, reading, and writing config files
  license: BSD-3-Clause
  license_file: LICENSE
